# Generated by Django 3.1.7 on 2021-03-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название бренда')),
                ('korea_name', models.CharField(max_length=100, verbose_name='Корейское название бренда')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('korea_name', models.CharField(max_length=100, verbose_name='Корейское название модели')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.brand')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='CarOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Опция')),
                ('korea_name', models.CharField(max_length=100, verbose_name='Корейское название')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
            ],
            options={
                'verbose_name': 'Опиция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('korea_name', models.CharField(max_length=100, verbose_name='Корейкое название цвета')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='GasolineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название типа топлива')),
                ('korea_name', models.CharField(max_length=40, verbose_name='Корейское название топлива')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='TransmissionsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип трансмисии')),
                ('korea_name', models.CharField(max_length=40, verbose_name='Корейское название типа')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
            ],
            options={
                'verbose_name': 'Трансмисия',
                'verbose_name_plural': 'Трансмисии',
            },
        ),
        migrations.CreateModel(
            name='CarVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Версия модели')),
                ('korea_name', models.CharField(max_length=100, verbose_name='Корейское название модели')),
                ('code', models.IntegerField(verbose_name='Код на корейском сайте')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.carmodel')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_code', models.IntegerField(verbose_name='Код на сайте')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('image_count', models.IntegerField(default=0, verbose_name='Кол-во изображений')),
                ('car_LPG_use', models.BooleanField(default=False, verbose_name='Испольузет ГАЗ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.color', verbose_name='Цвет')),
                ('gasoline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.gasolinetype', verbose_name='Тип топлива')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.carversion', verbose_name='Версия модели')),
                ('options', models.ManyToManyField(to='list_auto.CarOptions', verbose_name='Опции')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_auto.transmissionstype', verbose_name='Трансмисия')),
            ],
        ),
    ]
