# Generated by Django 3.1.7 on 2021-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carversion',
            options={'verbose_name': 'Версия Модели', 'verbose_name_plural': 'Версия Модели'},
        ),
        migrations.AddField(
            model_name='car',
            name='jesi_no',
            field=models.IntegerField(default=0, verbose_name='JESI site code'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='', max_length=15, verbose_name='Номерной знак'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(default=' ', max_length=25, verbose_name='VIN CODE'),
            preserve_default=False,
        ),
    ]
