# Generated by Django 3.1.7 on 2021-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0002_auto_20210308_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='first_register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первой регистации'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
