# Generated by Django 3.1.7 on 2021-03-11 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0005_auto_20210309_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_smear',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Наличие пятен'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_transformation',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Наличие модификаций (изменений)'),
        ),
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата добавления в БД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='lot_register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания лота'),
        ),
    ]
