# Generated by Django 3.1.7 on 2021-03-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0006_auto_20210311_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='carversion',
            name='engine_volume',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='carversion',
            name='four_wd',
            field=models.BooleanField(blank=True, null=True, verbose_name='4WD'),
        ),
    ]
