# Generated by Django 3.1.7 on 2021-03-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0007_auto_20210313_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип кузова')),
            ],
        ),
        migrations.AddField(
            model_name='carversion',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list_auto.bodytype', verbose_name='Тип кузова'),
        ),
    ]
