# Generated by Django 3.1.7 on 2021-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0008_auto_20210313_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name': 'Тип кузова', 'verbose_name_plural': 'Типы кузова'},
        ),
        migrations.AddField(
            model_name='caroptions',
            name='option_group',
            field=models.IntegerField(default=0, verbose_name='Код гурппы опций'),
        ),
    ]
