# Generated by Django 3.1.7 on 2021-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0009_auto_20210314_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в БД'),
        ),
    ]
