# Generated by Django 3.1.7 on 2021-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0010_auto_20210326_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='VIN CODE'),
        ),
    ]
